ALTER TABLE cafes ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE menu_items ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE schedules ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE rates ADD COLUMN updated_at TIMESTAMP;

