-- ============================================================
-- Cafes data - generated from CoffeeData_Cafes CSV
-- ============================================================

INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('KAFFE BAGERI Stockholm', 'Podbrzezie 2, 31-054 Kraków', TRUE, NULL, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('CYTAT Café', 'Miodowa 23, 31-055 Kraków', NULL, TRUE, TRUE, NULL, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Blumen Café', 'Świętego Sebastiana 31, 31-051 Kraków', NULL, TRUE, TRUE, NULL, NULL, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Mleczarnia', 'Rabina, Beera Meiselsa 20, 31-058 Kraków', NULL, TRUE, TRUE, NULL, NULL, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('COFFEE GARDEN', 'Józefa 11, 31-056 Kraków', TRUE, TRUE, TRUE, NULL, NULL, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('FINCA COFFEE', 'Józefa 11, 31-056 Kraków', TRUE, TRUE, TRUE, NULL, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Cafe Kładka', 'Mostowa 12, 31-061 Kraków', NULL, TRUE, TRUE, NULL, NULL, TRUE, FALSE, TRUE, FALSE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Urban Coffee', 'plac Wolnica 12A, 31-060 Kraków', TRUE, TRUE, TRUE, NULL, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Somnium Cafe Bar', 'Beera Meiselsa 5, 31-062 Kraków', NULL, TRUE, TRUE, NULL, NULL, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Carmel Atelier', 'Starowiślna 77, 31-052 Kraków', TRUE, TRUE, TRUE, NULL, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('KawaLerka', 'Brzozowa 20, 31-050 Kraków', TRUE, TRUE, TRUE, NULL, NULL, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Urban Coffee', 'Kalwaryjska 96, 30-504 Kraków', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Mech Café', 'Jana Zamoyskiego, 33-332 Kraków', FALSE, TRUE, TRUE, FALSE, NULL, FALSE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Ambalaż - kawiarnia z widokiem', 'Nadwiślańska 2/4, 30-527 Kraków', TRUE, TRUE, TRUE, NULL, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Cawa', 'Nadwiślańska 1, 30-527 Kraków', TRUE, NULL, TRUE, TRUE, NULL, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('EMIGRANT Specialty Coffee – Kalwaryjska', 'Kalwaryjska 1, 30-509 Kraków', TRUE, TRUE, TRUE, NULL, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('La Baguette', 'Zabłocie 19, 30-701 Kraków', TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Coffeece', 'Przemysłowa 12, 30-701 Kraków', TRUE, TRUE, TRUE, FALSE, NULL, NULL, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Aftertaste Coffee & Wine', 'Plac Bohaterów Getta 17, 30-547 Kraków', TRUE, NULL, TRUE, TRUE, NULL, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('iOVE Cocktail I Coffee I Music I Fashion I Breakfast', 'Zabłocie 19A/186, 30-701 Kraków', TRUE, NULL, TRUE, FALSE, NULL, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Rozkwit cafe', 'Kalwaryjska 34/LU1, 30-504 Kraków', TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Bonbon Boutique', 'Nadwiślańska 11, 33-332 Kraków', TRUE, TRUE, TRUE, NULL, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Søtt Cafe & Bakery • Specialty Coffee • Breakfasts', 'Lwowska 1, 30-548 Kraków', TRUE, TRUE, TRUE, FALSE, NULL, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Fable Cafe', 'Rajska 20, 31-124 Kraków', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Efemeria. Kraina Czarów', 'Karmelicka 7, 31-133 Kraków', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Magia Bar Cafe', 'plac Mariacki 3, 31-042 Kraków', TRUE, FALSE, TRUE, TRUE, NULL, TRUE, TRUE, TRUE, FALSE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Butter Café', 'św. Marka 23, 31-020 Kraków', NULL, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Żarówka Cafe', 'Floriańska 20, 31-021 Kraków', TRUE, TRUE, TRUE, TRUE, NULL, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Cakester Cafe', 'Św. Tomasza 25, 31-027 Kraków', TRUE, FALSE, TRUE, NULL, NULL, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Katane', 'Szpitalna 40, 31-024 Kraków', NULL, FALSE, TRUE, NULL, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Dziórawy Kocioł', 'Grodzka 50/1, 31-044 Kraków', TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Nowa Prowincja', 'Bracka 3, do 5, 31-005 Kraków', TRUE, TRUE, TRUE, TRUE, NULL, TRUE, TRUE, TRUE, FALSE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('Charlotte', 'plac Szczepański 2, 31-011 Kraków', TRUE, TRUE, TRUE, NULL, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('B.O.H.O Coffee&Bar', 'Stolarska 6, 31-044 Kraków', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO cafes (name, address, has_wifi, allows_pets, sells_food, allows_students_discounts, is_lgbtq_friendly, has_toilet, has_terrace, allows_intake, allows_takeaway, supports_card_payments) VALUES ('De revolutionibus ideæ', 'Bracka 14, 31-005 Kraków', NULL, FALSE, TRUE, NULL, NULL, TRUE, FALSE, TRUE, FALSE, TRUE);